name: tests
run-name: Run Tests
on:
  pull_request:
    branches: [master]
jobs:
  database_tests:
    name: Database tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run tests
        run: |
          'chmod +x ./test_database.sh'
          './test_database.sh'
